Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.SendKeys "^{ESC}"
WScript.Sleep 1000
WshShell.SendKeys "defender"
WScript.Sleep 1000
WshShell.SendKeys "{ENTER}"
WScript.Sleep 8000
WshShell.SendKeys "{TAB}"
WScript.Sleep 1000
WshShell.SendKeys "{TAB}"
WScript.Sleep 1000
WshShell.SendKeys "{DOWN}"
WScript.Sleep 1000
WshShell.SendKeys "{ENTER}"
WScript.Sleep 1000
WshShell.SendKeys "{TAB}"
WScript.Sleep 1000
WshShell.SendKeys "{TAB}"
WScript.Sleep 1000
WshShell.SendKeys "{TAB}"
WScript.Sleep 1000
WshShell.SendKeys "{TAB}"
WScript.sleep 1000
WshShell.SendKeys "{ENTER}"
WScript.sleep 1000
WshShell.SendKeys "{SPACE}"
WScript.Sleep 1000
WshShell.SendKeys "{LEFT}"
WScript.Sleep 10001
WshShell.SendKeys "{ENTER}"